import { z } from 'zod';

export const scannerPreferenceSchema = z.object({
  targetKeywords: z
    .array(z.string().min(1))
    .min(1, 'At least one target role keyword is required (e.g. Frontend Developer)'),
  minMatchScore: z.coerce.number().min(30).max(100).default(70),
  targetGroupUrl: z.string().url('Invalid group URL').or(z.literal('')).nullable().optional(),
  autoGenerateDraft: z.boolean().default(true),
});

export const singleFacebookPostSchema = z.object({
  content: z.string().min(10, 'Post content must be at least 10 characters'),
  postUrl: z.string().url('Invalid post URL').or(z.literal('')).nullable().optional(),
  author: z.string().nullable().optional(),
});

export const scanFeedPayloadSchema = z.object({
  posts: z.array(singleFacebookPostSchema).min(1, 'Please provide at least one post to scan'),
  autoGenerateDraft: z.boolean().optional(),
});

export type ScannerPreferenceInput = z.infer<typeof scannerPreferenceSchema>;
export type SingleFacebookPostInput = z.infer<typeof singleFacebookPostSchema>;
export type ScanFeedPayloadInput = z.infer<typeof scanFeedPayloadSchema>;
