import crypto from 'crypto';
import prisma from '@/lib/prisma';
import { getUserProfile } from '@/services/profile.service';
import { generateApplicationEmail } from '@/services/ai.service';
import { logApplicationEvent } from '@/services/application.service';
import { UserProfile } from '@/types';
import { RawFacebookPostInput, ScannerPreferenceData, ScannerStats } from './facebook.types';
import { parseFacebookJobPost } from './facebookParser.service';
import { DEFAULT_TARGET_KEYWORDS, evaluateFacebookJobMatch } from './facebookMatcher.service';

/**
 * Computes deterministic SHA-256 hash of post content for deduplication.
 */
export function computePostHash(content: string): string {
  const normalized = content.replace(/\s+/g, ' ').trim().toLowerCase();
  return crypto.createHash('sha256').update(normalized).digest('hex');
}

/**
 * Fetches user scanner preferences or initializes default.
 */
export async function getScannerPreferences(userId: string): Promise<ScannerPreferenceData> {
  const pref = await prisma.scannerPreference.findUnique({
    where: { userId },
  });

  if (!pref) {
    return {
      targetKeywords: DEFAULT_TARGET_KEYWORDS,
      minMatchScore: 70,
      targetGroupUrl: null,
      autoGenerateDraft: true,
    };
  }

  return {
    targetKeywords: pref.targetKeywords,
    minMatchScore: pref.minMatchScore,
    targetGroupUrl: pref.targetGroupUrl,
    autoGenerateDraft: pref.autoGenerateDraft,
  };
}

/**
 * Updates scanner preferences for a user.
 */
export async function upsertScannerPreferences(
  userId: string,
  data: Partial<ScannerPreferenceData>
): Promise<ScannerPreferenceData> {
  const updated = await prisma.scannerPreference.upsert({
    where: { userId },
    update: {
      targetKeywords: data.targetKeywords,
      minMatchScore: data.minMatchScore,
      targetGroupUrl: data.targetGroupUrl ?? null,
      autoGenerateDraft: data.autoGenerateDraft ?? true,
      updatedAt: new Date(),
    },
    create: {
      userId,
      targetKeywords: data.targetKeywords || DEFAULT_TARGET_KEYWORDS,
      minMatchScore: data.minMatchScore || 70,
      targetGroupUrl: data.targetGroupUrl ?? null,
      autoGenerateDraft: data.autoGenerateDraft ?? true,
    },
  });

  return {
    targetKeywords: updated.targetKeywords,
    minMatchScore: updated.minMatchScore,
    targetGroupUrl: updated.targetGroupUrl,
    autoGenerateDraft: updated.autoGenerateDraft,
  };
}

/**
 * Retrieves overall scanner statistics for dashboard.
 */
export async function getScannerStats(userId: string): Promise<ScannerStats> {
  const [totalScanned, relevantJobs, draftApplications, ignored] = await Promise.all([
    prisma.facebookPost.count({ where: { userId } }),
    prisma.facebookPost.count({ where: { userId, isRelevant: true } }),
    prisma.facebookPost.count({ where: { userId, applicationId: { not: null } } }),
    prisma.facebookPost.count({ where: { userId, isIgnored: true } }),
  ]);

  return {
    totalScanned,
    relevantJobs,
    draftApplications,
    ignored,
  };
}

/**
 * Core Facebook Job Batch Ingestion & Processing.
 *
 * CRITICAL SAFETY INVARIANT:
 * Automation only ingests, analyzes, and prepares DRAFT emails.
 * NEVER sends any email autonomously.
 */
export async function processFacebookPosts(
  userId: string,
  rawPosts: RawFacebookPostInput[]
): Promise<{
  scanned: number;
  newProcessed: number;
  relevantCount: number;
  draftsCreated: number;
  results: any[];
}> {
  const profileData = await getUserProfile(userId);
  const preferences = await getScannerPreferences(userId);

  if (!profileData) {
    throw new Error('User profile not found. Please complete profile before running scanner.');
  }

  const profile: UserProfile = {
    fullName: profileData.fullName,
    title: profileData.title,
    yearsOfExperience: profileData.yearsOfExperience,
    summary: profileData.summary,
    skills: profileData.skills,
    projects: profileData.projects || [],
    experiences: profileData.experiences || [],
    education: profileData.education || [],
    portfolio: profileData.portfolio,
    phone: profileData.phone,
  };

  let newProcessed = 0;
  let relevantCount = 0;
  let draftsCreated = 0;
  const processedResults: any[] = [];

  for (const raw of rawPosts) {
    const postHash = computePostHash(raw.content);

    // Check duplicate
    const existing = await prisma.facebookPost.findUnique({
      where: { postHash },
      include: { application: true },
    });

    if (existing) {
      processedResults.push({
        postHash,
        status: 'DUPLICATE_SKIPPED',
        isRelevant: existing.isRelevant,
        applicationId: existing.applicationId,
      });
      continue;
    }

    newProcessed++;

    // 1. Parse Social Job Post
    const parsed = parseFacebookJobPost(raw);

    // 2. Evaluate Match against candidate profile & keywords
    const evaluation = evaluateFacebookJobMatch(
      parsed,
      profile,
      preferences.targetKeywords,
      preferences.minMatchScore
    );

    let createdApplicationId: string | null = null;

    // 3. If Relevant & Auto-Draft Enabled -> Generate Factual Application Draft
    if (evaluation.isRelevant && preferences.autoGenerateDraft) {
      relevantCount++;

      // Synthesize factual customized email draft (strictly using candidate's real profile)
      const emailDraft = await generateApplicationEmail(profile, {
        companyName: parsed.company,
        jobTitle: parsed.title,
        requiredSkills: parsed.requiredSkills,
        preferredSkills: parsed.preferredSkills,
        jobDescription: parsed.description,
      });

      const fullEmailBody = `${emailDraft.greeting}\n\n${emailDraft.body}\n\n${emailDraft.closing}\n${emailDraft.signature}`;

      // Create JobApplication in DRAFT state
      const application = await prisma.jobApplication.create({
        data: {
          userId,
          companyName: parsed.company,
          jobTitle: parsed.title,
          jobUrl: raw.postUrl || null,
          jobDescription: parsed.description,
          workType: parsed.workType || 'Unknown',
          location: parsed.location || null,
          recipientEmail: parsed.recipientEmail,
          subject: emailDraft.subject,
          emailBody: fullEmailBody,
          status: 'DRAFT', // STRICTLY DRAFT - NEVER AUTO-SENT
          matchScore: evaluation.matchScore,
          matchBreakdown: {
            strongMatches: evaluation.strongMatches,
            missingSkills: evaluation.missingSkills,
            matchedKeyword: evaluation.matchedKeyword,
            reason: evaluation.reason,
          },
          notes: `Ingested from Facebook Job Feed.\nMatched Role: ${evaluation.matchedKeyword || parsed.title}\nCandidate Match: ${evaluation.matchScore}%`,
        },
      });

      createdApplicationId = application.id;
      draftsCreated++;

      // Log event
      await logApplicationEvent({
        applicationId: application.id,
        eventType: 'DRAFT_GENERATED_FROM_FACEBOOK',
        description: `Draft application generated from Facebook job post (${parsed.title} at ${parsed.company})`,
        metadata: {
          postUrl: raw.postUrl,
          matchScore: evaluation.matchScore,
          matchedKeyword: evaluation.matchedKeyword,
        },
      });
    }

    // 4. Record FacebookPost in Database
    const savedPost = await prisma.facebookPost.create({
      data: {
        userId,
        postUrl: raw.postUrl || null,
        postHash,
        rawContent: raw.content,
        extractedTitle: parsed.title,
        extractedCompany: parsed.company,
        extractedEmail: parsed.recipientEmail,
        extractedSkills: parsed.requiredSkills,
        matchScore: evaluation.matchScore,
        isRelevant: evaluation.isRelevant,
        isIgnored: false,
        applicationId: createdApplicationId,
      },
    });

    processedResults.push({
      id: savedPost.id,
      postHash,
      title: parsed.title,
      company: parsed.company,
      email: parsed.recipientEmail,
      isRelevant: evaluation.isRelevant,
      matchScore: evaluation.matchScore,
      applicationId: createdApplicationId,
      status: evaluation.isRelevant ? 'RELEVANT_DRAFT_READY' : 'IGNORED_BELOW_THRESHOLD',
    });
  }

  return {
    scanned: rawPosts.length,
    newProcessed,
    relevantCount,
    draftsCreated,
    results: processedResults,
  };
}
