export interface RawFacebookPostInput {
  content: string;
  postUrl?: string | null;
  postHash?: string;
  author?: string | null;
  timestamp?: string | null;
}

export interface ParsedFacebookJob {
  title: string;
  company: string;
  description: string;
  requiredSkills: string[];
  preferredSkills: string[];
  recipientEmail: string | null;
  location?: string;
  workType?: 'Remote' | 'Hybrid' | 'Onsite' | 'Unknown';
  experience?: string;
  isJobPost: boolean;
}

export interface FacebookMatchEvaluation {
  isRelevant: boolean;
  matchScore: number;
  matchedKeyword: string | null;
  strongMatches: string[];
  missingSkills: string[];
  reason: string;
}

export interface ScannerStats {
  totalScanned: number;
  relevantJobs: number;
  draftApplications: number;
  ignored: number;
}

export interface ScannerPreferenceData {
  targetKeywords: string[];
  minMatchScore: number;
  targetGroupUrl?: string | null;
  autoGenerateDraft: boolean;
}
