'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import {
  Sparkles,
  Search,
  Filter,
  RefreshCw,
  ExternalLink,
  Mail,
  CheckCircle2,
  XCircle,
  Eye,
  Sliders,
  Play,
  ArrowRight,
  ShieldCheck,
  Building2,
  Trash2,
  Layers,
  Plus,
} from 'lucide-react';
import { Card, CardHeader, CardContent, CardFooter } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Alert } from '@/components/ui/Alert';
import { Modal } from '@/components/ui/Modal';
import { Skeleton } from '@/components/ui/Skeleton';
import { ScannerPreferenceData, ScannerStats } from '@/services/facebook/facebook.types';

export default function FacebookScannerPage() {
  const [stats, setStats] = useState<ScannerStats>({
    totalScanned: 0,
    relevantJobs: 0,
    draftApplications: 0,
    ignored: 0,
  });
  const [posts, setPosts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [isScanning, setIsScanning] = useState(false);
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  // Filter State
  const [feedFilter, setFeedFilter] = useState<'all' | 'relevant' | 'drafts' | 'ignored'>('all');

  // Preferences State
  const [preferences, setPreferences] = useState<ScannerPreferenceData>({
    targetKeywords: [
      'Frontend Developer',
      'React Developer',
      'Next.js Developer',
      'MERN Stack Developer',
      'Full Stack Developer',
    ],
    minMatchScore: 70,
    targetGroupUrl: null,
    autoGenerateDraft: true,
  });
  const [isSavingPrefs, setIsSavingPrefs] = useState(false);
  const [newKeywordInput, setNewKeywordInput] = useState('');

  // Paste Feed Modal
  const [isPasteModalOpen, setIsPasteModalOpen] = useState(false);
  const [pastedContent, setPastedContent] = useState('');
  const [pastedUrl, setPastedUrl] = useState('');

  const fetchScannerData = async () => {
    try {
      const [scannerRes, prefsRes] = await Promise.all([
        fetch('/api/facebook/scanner'),
        fetch('/api/facebook/preferences'),
      ]);

      const scannerJson = await scannerRes.json();
      if (scannerJson.success && scannerJson.data) {
        setStats(scannerJson.data.stats);
        setPosts(scannerJson.data.posts);
      }

      const prefsJson = await prefsRes.json();
      if (prefsJson.success && prefsJson.data) {
        setPreferences(prefsJson.data);
      }
    } catch (err) {
      console.error('Failed to load scanner data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchScannerData();
  }, []);

  // Trigger Automatic Feed Scan
  const handleTriggerScan = async (customPosts?: any[]) => {
    setIsScanning(true);
    setFeedback(null);
    try {
      const res = await fetch('/api/facebook/scan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: customPosts ? JSON.stringify({ posts: customPosts }) : JSON.stringify({}),
      });

      const json = await res.json();
      if (!res.ok || !json.success) {
        throw new Error(json.error || 'Failed to scan Facebook feed');
      }

      setFeedback({ type: 'success', message: json.message });
      fetchScannerData();
      setIsPasteModalOpen(false);
      setPastedContent('');
    } catch (err: any) {
      setFeedback({ type: 'error', message: err.message || 'Error scanning feed' });
    } finally {
      setIsScanning(false);
    }
  };

  const handleIgnorePost = async (postId: string) => {
    try {
      const res = await fetch(`/api/facebook/posts/${postId}/ignore`, { method: 'PATCH' });
      const json = await res.json();
      if (json.success) {
        fetchScannerData();
      }
    } catch (err) {
      console.error('Failed to ignore post:', err);
    }
  };

  const handleSavePreferences = async () => {
    setIsSavingPrefs(true);
    try {
      const res = await fetch('/api/facebook/preferences', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(preferences),
      });
      const json = await res.json();
      if (json.success) {
        setFeedback({ type: 'success', message: 'Matching preferences saved successfully!' });
        setTimeout(() => setFeedback(null), 3000);
      }
    } catch (err: any) {
      setFeedback({ type: 'error', message: err.message || 'Error saving preferences' });
    } finally {
      setIsSavingPrefs(false);
    }
  };

  const handleAddKeyword = (e: React.KeyboardEvent | React.MouseEvent) => {
    if ('key' in e && e.key !== 'Enter') return;
    e.preventDefault();
    const val = newKeywordInput.trim();
    if (val && !preferences.targetKeywords.includes(val)) {
      setPreferences({
        ...preferences,
        targetKeywords: [...preferences.targetKeywords, val],
      });
      setNewKeywordInput('');
    }
  };

  const handleRemoveKeyword = (kw: string) => {
    setPreferences({
      ...preferences,
      targetKeywords: preferences.targetKeywords.filter(k => k !== kw),
    });
  };

  const filteredPosts = posts.filter(post => {
    if (feedFilter === 'relevant') return post.isRelevant && !post.isIgnored;
    if (feedFilter === 'drafts') return post.applicationId !== null;
    if (feedFilter === 'ignored') return post.isIgnored;
    return true;
  });

  return (
    <div className="space-y-8 max-w-5xl mx-auto pb-16">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-900 p-6 rounded-2xl text-white shadow-md">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-semibold uppercase tracking-wider text-blue-300">
              Social Job Discovery
            </span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight">Facebook Job Feed Scanner</h1>
          <p className="text-blue-200 text-xs mt-1 max-w-xl">
            Automatically reads social job postings, matches target roles against your factual profile, and prepares tailored email drafts for your review.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            size="md"
            variant="outline"
            onClick={() => setIsPasteModalOpen(true)}
            className="bg-white/10 hover:bg-white/20 text-white border-white/20 text-xs"
          >
            Paste Feed Text
          </Button>
          <Button
            size="md"
            onClick={() => handleTriggerScan()}
            isLoading={isScanning}
            className="bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs shadow"
            leftIcon={<Play className="w-4 h-4 fill-white" />}
          >
            Scan Facebook Feed
          </Button>
        </div>
      </div>

      {feedback && (
        <Alert
          type={feedback.type}
          message={feedback.message}
          onClose={() => setFeedback(null)}
        />
      )}

      {/* Safety Notice */}
      <div className="p-3.5 rounded-xl bg-emerald-50 border border-emerald-200 text-xs text-emerald-900 flex items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <ShieldCheck className="w-5 h-5 text-emerald-600 flex-shrink-0" />
          <span>
            <strong>Zero-Auto-Send Policy Enforced:</strong> The scanner only generates <strong>DRAFT</strong> emails. You maintain complete human review and must check all 4 confirmation boxes before any email is sent.
          </span>
        </div>
      </div>

      {/* Top 4 Stats Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <Card className="p-4">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            Scanned Posts
          </span>
          <span className="text-2xl font-extrabold text-slate-900 mt-1 block">
            {stats.totalScanned}
          </span>
        </Card>

        <Card className="p-4 border-indigo-200 bg-indigo-50/20">
          <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-700 block">
            Relevant Jobs
          </span>
          <span className="text-2xl font-extrabold text-indigo-900 mt-1 block">
            {stats.relevantJobs}
          </span>
        </Card>

        <Card className="p-4 border-emerald-200 bg-emerald-50/20">
          <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-700 block">
            Email Drafts Ready
          </span>
          <span className="text-2xl font-extrabold text-emerald-900 mt-1 block">
            {stats.draftApplications}
          </span>
        </Card>

        <Card className="p-4">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
            Ignored / Filtered
          </span>
          <span className="text-2xl font-extrabold text-slate-600 mt-1 block">
            {stats.ignored}
          </span>
        </Card>
      </div>

      {/* Matching Preferences Card */}
      <Card>
        <CardHeader
          title="Job Matching Preferences"
          subtitle="Customize which roles the scanner targets and the minimum profile match score required to generate a draft email"
          action={
            <Button
              size="sm"
              variant="secondary"
              onClick={handleSavePreferences}
              isLoading={isSavingPrefs}
            >
              Save Preferences
            </Button>
          }
        />
        <CardContent className="space-y-4">
          {/* Target Role Keywords */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Target Role Keywords
            </label>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={newKeywordInput}
                onChange={e => setNewKeywordInput(e.target.value)}
                onKeyDown={handleAddKeyword}
                placeholder="Add role keyword (e.g. MERN Developer, React Developer)..."
                className="flex-1 px-3 py-1.5 text-xs border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
              />
              <Button type="button" size="sm" onClick={handleAddKeyword} leftIcon={<Plus className="w-3.5 h-3.5" />}>
                Add
              </Button>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {preferences.targetKeywords.map(kw => (
                <span
                  key={kw}
                  className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-medium bg-blue-50 text-blue-800 border border-blue-200"
                >
                  {kw}
                  <button
                    type="button"
                    onClick={() => handleRemoveKeyword(kw)}
                    className="text-blue-400 hover:text-blue-600"
                  >
                    &times;
                  </button>
                </span>
              ))}
            </div>
          </div>

          {/* Minimum Match Score Threshold */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
            <div>
              <div className="flex justify-between items-center mb-1">
                <label className="text-xs font-semibold text-slate-700">
                  Minimum Match Score Threshold
                </label>
                <span className="font-bold text-indigo-600 text-xs">{preferences.minMatchScore}%</span>
              </div>
              <input
                type="range"
                min={40}
                max={95}
                step={5}
                value={preferences.minMatchScore}
                onChange={e =>
                  setPreferences({ ...preferences, minMatchScore: Number(e.target.value) })
                }
                className="w-full accent-indigo-600"
              />
              <p className="text-[11px] text-slate-400 mt-1">
                Posts scoring below {preferences.minMatchScore}% will be filtered out to prevent spam.
              </p>
            </div>

            <div className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 border border-slate-200/80">
              <input
                type="checkbox"
                id="autoDraft"
                checked={preferences.autoGenerateDraft}
                onChange={e =>
                  setPreferences({ ...preferences, autoGenerateDraft: e.target.checked })
                }
                className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500 w-4 h-4"
              />
              <label htmlFor="autoDraft" className="text-xs text-slate-700 font-medium cursor-pointer">
                <strong>Auto-generate Email Draft:</strong> When a post matches &gt;= {preferences.minMatchScore}%, automatically synthesize a factual draft email ready for your review.
              </label>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Scanned Posts Feed & Review Section */}
      <Card>
        <CardHeader
          title="Scanned Facebook Posts"
          subtitle="Filtered opportunities discovered from social developer feeds"
          action={
            <div className="flex items-center gap-1 bg-slate-100 p-1 rounded-lg">
              <button
                onClick={() => setFeedFilter('all')}
                className={`px-2.5 py-1 text-xs font-semibold rounded-md transition ${
                  feedFilter === 'all' ? 'bg-white shadow-xs text-slate-900' : 'text-slate-500'
                }`}
              >
                All ({posts.length})
              </button>
              <button
                onClick={() => setFeedFilter('relevant')}
                className={`px-2.5 py-1 text-xs font-semibold rounded-md transition ${
                  feedFilter === 'relevant' ? 'bg-white shadow-xs text-indigo-700' : 'text-slate-500'
                }`}
              >
                Relevant ({posts.filter(p => p.isRelevant && !p.isIgnored).length})
              </button>
              <button
                onClick={() => setFeedFilter('drafts')}
                className={`px-2.5 py-1 text-xs font-semibold rounded-md transition ${
                  feedFilter === 'drafts' ? 'bg-white shadow-xs text-emerald-700' : 'text-slate-500'
                }`}
              >
                Drafts Ready ({posts.filter(p => p.applicationId).length})
              </button>
              <button
                onClick={() => setFeedFilter('ignored')}
                className={`px-2.5 py-1 text-xs font-semibold rounded-md transition ${
                  feedFilter === 'ignored' ? 'bg-white shadow-xs text-slate-600' : 'text-slate-500'
                }`}
              >
                Ignored ({posts.filter(p => p.isIgnored).length})
              </button>
            </div>
          }
        />
        <CardContent className="p-0">
          {loading ? (
            <div className="p-6 space-y-4">
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
              <Skeleton className="h-24 w-full" />
            </div>
          ) : filteredPosts.length === 0 ? (
            <div className="p-12 text-center space-y-3">
              <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center mx-auto">
                <Search className="w-6 h-6" />
              </div>
              <h4 className="font-semibold text-slate-800 text-sm">No posts in this view</h4>
              <p className="text-xs text-slate-500 max-w-sm mx-auto">
                Click &quot;Scan Facebook Feed&quot; to ingest sample posts or paste custom group text.
              </p>
              <Button size="sm" onClick={() => handleTriggerScan()} isLoading={isScanning}>
                Run Scanner Now
              </Button>
            </div>
          ) : (
            <div className="divide-y divide-slate-100">
              {filteredPosts.map(post => (
                <div key={post.id} className="p-5 hover:bg-slate-50/70 transition space-y-3">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="font-bold text-slate-900 text-sm">
                          {post.extractedTitle || 'Software Position'}
                        </h3>
                        {post.matchScore !== null && (
                          <span
                            className={`px-2 py-0.5 rounded-full text-[10px] font-extrabold border ${
                              post.matchScore >= preferences.minMatchScore
                                ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                                : 'bg-slate-100 text-slate-600 border-slate-200'
                            }`}
                          >
                            {post.matchScore}% Match
                          </span>
                        )}
                        {post.applicationId && (
                          <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-indigo-100 text-indigo-800">
                            Email Draft Ready
                          </span>
                        )}
                        {post.isIgnored && (
                          <span className="px-2 py-0.5 rounded-full text-[10px] font-medium bg-slate-100 text-slate-500">
                            Ignored
                          </span>
                        )}
                      </div>
                      <div className="text-xs text-slate-500 flex items-center gap-2 mt-0.5">
                        <span className="font-medium text-slate-700 flex items-center gap-1">
                          <Building2 className="w-3.5 h-3.5 text-slate-400" />
                          {post.extractedCompany}
                        </span>
                        <span>•</span>
                        <span>Source: Facebook</span>
                        <span>•</span>
                        <span>{new Date(post.scannedAt).toLocaleDateString()}</span>
                      </div>
                    </div>

                    {/* Action Buttons */}
                    <div className="flex items-center gap-2 pt-1 sm:pt-0">
                      {post.applicationId ? (
                        <Link href={`/applications/${post.applicationId}`}>
                          <Button size="sm" variant="primary" rightIcon={<ArrowRight className="w-3.5 h-3.5" />}>
                            Review Email Draft
                          </Button>
                        </Link>
                      ) : (
                        post.isRelevant && (
                          <Link href="/applications/new">
                            <Button size="sm" variant="outline">
                              Apply
                            </Button>
                          </Link>
                        )
                      )}

                      {!post.isIgnored && (
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => handleIgnorePost(post.id)}
                          className="text-slate-400 hover:text-slate-600 text-xs"
                        >
                          Ignore
                        </Button>
                      )}

                      {post.postUrl && (
                        <a
                          href={post.postUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="p-1.5 rounded-md text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition"
                          title="Open Facebook Post"
                        >
                          <ExternalLink className="w-4 h-4" />
                        </a>
                      )}
                    </div>
                  </div>

                  {/* Recipient Email & Detected Skills */}
                  <div className="flex flex-wrap items-center gap-3 text-xs">
                    {post.extractedEmail ? (
                      <div className="flex items-center gap-1.5 font-mono text-slate-800 bg-slate-100 px-2 py-1 rounded">
                        <Mail className="w-3.5 h-3.5 text-indigo-600" />
                        <span>{post.extractedEmail}</span>
                      </div>
                    ) : (
                      <span className="text-slate-400 italic">No email found in post</span>
                    )}

                    {post.extractedSkills && post.extractedSkills.length > 0 && (
                      <div className="flex items-center gap-1 flex-wrap">
                        {post.extractedSkills.map((s: string, idx: number) => (
                          <span
                            key={idx}
                            className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-slate-100 text-slate-700"
                          >
                            {s}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Raw Post snippet */}
                  <div className="text-xs text-slate-600 font-sans whitespace-pre-line bg-slate-50/80 p-3 rounded-lg border border-slate-200/60 line-clamp-3">
                    {post.rawContent}
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Paste Feed Modal */}
      <Modal
        isOpen={isPasteModalOpen}
        onClose={() => setIsPasteModalOpen(false)}
        title="Paste Facebook Job Post / Feed"
      >
        <div className="space-y-4 text-xs">
          <p className="text-slate-600">
            Paste the raw text of one or more Facebook job postings from developer groups or hiring pages:
          </p>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Facebook Post URL (Optional)
            </label>
            <input
              type="url"
              value={pastedUrl}
              onChange={e => setPastedUrl(e.target.value)}
              placeholder="https://facebook.com/groups/.../posts/..."
              className="w-full px-3 py-2 text-xs border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Post Content <span className="text-rose-500">*</span>
            </label>
            <textarea
              rows={8}
              value={pastedContent}
              onChange={e => setPastedContent(e.target.value)}
              placeholder="Paste the Facebook job post text here..."
              className="w-full p-3 text-xs border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 font-mono leading-relaxed"
            />
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <Button variant="outline" size="sm" onClick={() => setIsPasteModalOpen(false)}>
              Cancel
            </Button>
            <Button
              size="sm"
              disabled={!pastedContent.trim()}
              isLoading={isScanning}
              onClick={() =>
                handleTriggerScan([
                  {
                    content: pastedContent,
                    postUrl: pastedUrl || null,
                  },
                ])
              }
            >
              Analyze &amp; Process Post
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
