const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('Testing connection to Neon PostgreSQL...');
  const users = await prisma.user.findMany();
  console.log('Connection successful! Current users:', users.length);
  
  // Create default user profile if none exists
  let user = await prisma.user.findFirst();
  if (!user) {
    user = await prisma.user.create({
      data: {
        id: 'default-user-id',
        email: 'developer@jobapply.ai',
        name: 'Tanvir Ahmed',
        profile: {
          create: {
            fullName: 'Tanvir Ahmed',
            title: 'MERN Stack & Full Stack Developer',
            yearsOfExperience: 3,
            summary: 'Passionate Frontend and MERN Stack Developer with 3+ years of experience building scalable web applications using React, Next.js, Node.js, Express, and PostgreSQL.',
            skills: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'Tailwind CSS', 'Redux', 'Prisma', 'REST API', 'Git', 'HTML5', 'CSS3'],
            location: 'Dhaka, Bangladesh',
            projects: {
              create: [
                {
                  title: 'JobApply AI Assistant',
                  description: 'AI-powered job application platform with Facebook job scanner and automated Gmail draft generation.',
                  techStack: ['Next.js', 'React', 'TypeScript', 'Prisma', 'PostgreSQL', 'Tailwind CSS'],
                  liveUrl: 'http://localhost:3000',
                  githubUrl: 'https://github.com/developer/jobapply-ai'
                },
                {
                  title: 'E-Commerce Platform',
                  description: 'Full-stack MERN e-commerce application with Stripe payment gateway, admin dashboard, and product reviews.',
                  techStack: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS']
                }
              ]
            },
            experiences: {
              create: [
                {
                  company: 'Tech Solutions Inc.',
                  role: 'Frontend / MERN Developer',
                  location: 'Remote',
                  startDate: '2023-01',
                  isCurrent: true,
                  description: 'Developing high-performance responsive web applications using React, Next.js, and TypeScript.',
                  achievements: ['Improved initial page load by 40% using Next.js SSR', 'Built reusable component library in Tailwind CSS']
                }
              ]
            }
          }
        },
        scannerPreference: {
          create: {
            targetKeywords: ['Frontend Developer', 'React Developer', 'Next.js Developer', 'MERN Stack Developer', 'Full Stack Developer'],
            minMatchScore: 70,
            autoGenerateDraft: true
          }
        }
      }
    });
    console.log('Seeded default user profile:', user.id, user.name);
  } else {
    console.log('Default user profile already present:', user.id, user.name);
  }
}

main()
  .catch((e) => {
    console.error('Database query failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
