import { describe, it, expect, vi, beforeEach } from 'vitest';
import { processFacebookPosts } from '@/services/facebook/facebookScanner.service';
import * as gmailService from '@/services/gmail.service';
import * as profileService from '@/services/profile.service';
import prisma from '@/lib/prisma';

// Mock Gmail service send function to verify it is NEVER called
vi.mock('@/services/gmail.service', () => ({
  sendGmailEmail: vi.fn(),
}));

describe('Facebook Job Scanner Integration & Safety Flow', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  const mockUserId = 'user-fb-123';

  it('CRITICAL: Ingests matching Facebook post, creates DRAFT application, and NEVER automatically sends', async () => {
    // Mock user profile
    vi.spyOn(profileService, 'getUserProfile').mockResolvedValue({
      id: 'profile-1',
      userId: mockUserId,
      fullName: 'Alex Morgan',
      title: 'Senior Full Stack Engineer',
      yearsOfExperience: 5,
      summary: 'Experienced Full Stack and MERN developer.',
      skills: ['React', 'Node.js', 'MongoDB', 'Express', 'TypeScript'],
      projects: [],
      experiences: [],
      education: [],
      github: null,
      linkedin: null,
      portfolio: null,
      phone: null,
      location: null,
    } as any);

    // Mock scanner preferences
    vi.spyOn(prisma.scannerPreference, 'findUnique').mockResolvedValue({
      id: 'pref-1',
      userId: mockUserId,
      targetKeywords: ['MERN Stack Developer', 'Frontend Developer'],
      minMatchScore: 70,
      targetGroupUrl: null,
      autoGenerateDraft: true,
      updatedAt: new Date(),
    });

    // Mock duplicate check returning null (first time seen)
    vi.spyOn(prisma.facebookPost, 'findUnique').mockResolvedValue(null);

    // Mock JobApplication creation
    vi.spyOn(prisma.jobApplication, 'create').mockResolvedValue({
      id: 'app-fb-1',
      userId: mockUserId,
      companyName: 'Apex Cloud Systems',
      jobTitle: 'MERN Stack Developer',
      status: 'DRAFT', // MUST BE DRAFT
      recipientEmail: 'recruiting@apexcloud.io',
      subject: 'Application for MERN Stack Developer - Alex Morgan',
      emailBody: 'Dear Hiring Team at Apex Cloud Systems...',
    } as any);

    // Mock FacebookPost creation
    vi.spyOn(prisma.facebookPost, 'create').mockResolvedValue({
      id: 'fb-post-1',
      userId: mockUserId,
      postHash: 'hash123',
      rawContent: 'Hiring MERN Stack Developer...',
      isRelevant: true,
      applicationId: 'app-fb-1',
    } as any);

    // Mock event logging
    vi.spyOn(prisma.applicationEvent, 'create').mockResolvedValue({ id: 'evt-1' } as any);

    const rawPosts = [
      {
        content: `🚀 Urgent Hiring: MERN Stack Developer (Remote)
Company: Apex Cloud Systems
We are actively hiring a MERN Stack Developer with React, Node.js, Express, and MongoDB.
Send resume to recruiting@apexcloud.io`,
        postUrl: 'https://facebook.com/groups/jobs/posts/999',
      },
    ];

    const result = await processFacebookPosts(mockUserId, rawPosts);

    expect(result.scanned).toBe(1);
    expect(result.relevantCount).toBe(1);
    expect(result.draftsCreated).toBe(1);
    expect(result.results[0].status).toBe('RELEVANT_DRAFT_READY');
    expect(result.results[0].applicationId).toBe('app-fb-1');

    // CRITICAL VERIFICATION:
    // Gmail sending MUST NEVER HAVE BEEN INVOKED!
    expect(gmailService.sendGmailEmail).not.toHaveBeenCalled();

    // Verify application created with status 'DRAFT'
    expect(prisma.jobApplication.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          status: 'DRAFT',
          companyName: 'Apex Cloud Systems',
          recipientEmail: 'recruiting@apexcloud.io',
        }),
      })
    );
  });
});
