import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import prisma from '@/lib/prisma';
import { hashPassword, createToken, AUTH_COOKIE_NAME } from '@/lib/auth-jwt';
import { formatErrorResponse } from '@/lib/errors';

const signupSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  email: z.string().email('Valid email address is required').toLowerCase(),
  password: z.string().min(6, 'Password must be at least 6 characters').max(100),
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { name, email, password } = signupSchema.parse(body);

    // Check if user already exists
    const existing = await prisma.user.findUnique({
      where: { email },
    });

    if (existing) {
      return NextResponse.json(
        { success: false, error: 'An account with this email already exists.' },
        { status: 409 }
      );
    }

    // Hash password with salt
    const passwordHash = await hashPassword(password);

    // Create user and initialize their profile and scanner preferences
    const user = await prisma.$transaction(async (tx) => {
      const newUser = await tx.user.create({
        data: {
          name,
          email,
          passwordHash,
          profile: {
            create: {
              fullName: name,
              title: 'Software Developer',
              yearsOfExperience: 1,
              summary: `Hello! I am ${name}, a software engineer passionate about modern web technologies.`,
              skills: ['React', 'JavaScript', 'TypeScript', 'Node.js', 'HTML5', 'CSS3', 'Tailwind CSS'],
            },
          },
          scannerPreference: {
            create: {
              targetKeywords: [
                'Frontend Developer',
                'React Developer',
                'Next.js Developer',
                'MERN Stack Developer',
                'Full Stack Developer',
              ],
              minMatchScore: 70,
              autoGenerateDraft: true,
            },
          },
        },
        select: {
          id: true,
          email: true,
          name: true,
          createdAt: true,
        },
      });

      return newUser;
    });

    // Create session token
    const token = createToken({
      userId: user.id,
      email: user.email,
      name: user.name,
    });

    const response = NextResponse.json(
      {
        success: true,
        message: 'Account created successfully.',
        user: {
          id: user.id,
          email: user.email,
          name: user.name,
        },
      },
      { status: 201 }
    );

    const isHttps =
      req.nextUrl.protocol === 'https:' ||
      req.headers.get('x-forwarded-proto') === 'https';

    // Set secure HTTP-only cookie
    response.cookies.set({
      name: AUTH_COOKIE_NAME,
      value: token,
      httpOnly: true,
      secure: isHttps,
      sameSite: 'lax',
      path: '/',
      maxAge: 60 * 60 * 24 * 7, // 7 days
    });

    return response;
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { success: false, error: error.errors[0]?.message || 'Invalid input' },
        { status: 400 }
      );
    }
    const err = formatErrorResponse(error);
    return NextResponse.json(err, { status: err.statusCode });
  }
}
